#!/usr/bin/env bash
# A Bash script that lists all running processes with hierarchy

ps -eo user,lstart,cmd --forest | awk 'BEGIN {print "USER STARTED COMMAND"} NR>1 {printf "%s %s %s %s %s %s ", $1, $2, $3, $4, $5, $6; for (i=7; i<=NF; i++) printf "%s ", $i; print ""}'

