#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
COUNTER=10
while [ $COUNTER -gt 0 ]; do
  if [ $COUNTER -eq 9 ]
  then
    echo "Hi"
  else
    echo "Best School"
  fi
  COUNTER=$((COUNTER - 1))
done
