#!/usr/bin/env bash
# This script displays numbers from 20 to 1, with special messages for some

COUNTER=20
while [ $COUNTER -gt 0 ]; do
  echo $COUNTER
  case $COUNTER in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  COUNTER=$((COUNTER - 1))
done
